export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const CONTACT_SELECTED = 'CONTACT_SELECTED';

export const BILL_LOADED = 'BILL_LOADED';
export const BILL_SELECTED = 'BILL_SELECTED';
export const BILL_REMOVED = 'BILL_REMOVED';
export const BILL_ADDED = 'BILL_ADDED';
export const BILL_UPDATED = 'BILL_UPDATED';
export const BILL_TRACKING_FETCHED = 'BILL_TRACKING_FETCHED';
export const BILL_REPORT_LOADED = 'BILL_REPORT_LOADED';

export const CUSTOMER_LOADED = 'CUSTOMER_LOADED';
export const CUSTOMER_ITEM_LOADED = 'CUSTOMER_ITEM_LOADED';
export const CUSTOMER_REPORT_LOADED = 'CUSTOMER_REPORT_LOADED';
export const CUSTOMER_UPDATED = 'CUSTOMER_UPDATED';
export const CUSTOMER_SELECTED = 'CUSTOMER_SELECTED';

